//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albumes
    {
        public Albumes()
        {
            this.Canciones = new HashSet<Canciones>();
        }
    
        public int CodigoAlbum { get; set; }
        public int CodigoArtista { get; set; }
        public string NombreAlbum { get; set; }
        public int AnoLanzamiento { get; set; }
        public string Imagen { get; set; }
    
        public virtual Artistas Artistas { get; set; }
        public virtual ICollection<Canciones> Canciones { get; set; }
    }
}
