//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artistas
    {
        public Artistas()
        {
            this.Albumes = new HashSet<Albumes>();
        }
    
        public int CodigoArtista { get; set; }
        public string NombreArtistico { get; set; }
        public string FechaNacimiento { get; set; }
        public string NombreReal { get; set; }
        public string Nacionalidad { get; set; }
        public string Foto { get; set; }
        public string LinkBiografia { get; set; }
    
        public virtual ICollection<Albumes> Albumes { get; set; }
    }
}
