//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canciones
    {
        public Canciones()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int CodigoCancion { get; set; }
        public int CodigoGenero { get; set; }
        public int CodigoAlbum { get; set; }
        public string NombreCancion { get; set; }
        public string LinkVideo { get; set; }
        public decimal Precio { get; set; }
        public int CantidadDisponible { get; set; }
    
        public virtual Albumes Albumes { get; set; }
        public virtual Generos Generos { get; set; }
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
    }
}
