//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int IDDetalle { get; set; }
        public int NumeroFactura { get; set; }
        public int CodigoCancion { get; set; }
        public decimal Subtotal { get; set; }
        public string NombreCancion { get; set; }
        public decimal PrecioUnitario { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Canciones Canciones { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
