//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class VentaMusicalEntities : DbContext
    {
        public VentaMusicalEntities()
            : base("name=VentaMusicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Albumes> Albumes { get; set; }
        public DbSet<Artistas> Artistas { get; set; }
        public DbSet<Auditoria> Auditoria { get; set; }
        public DbSet<Canciones> Canciones { get; set; }
        public DbSet<DetalleVenta> DetalleVenta { get; set; }
        public DbSet<Generos> Generos { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Ventas> Ventas { get; set; }
    
        public virtual int EditarDetalleVenta(Nullable<int> iDDetalle, Nullable<int> numeroFactura, Nullable<int> codigoCancion, Nullable<decimal> subtotal)
        {
            var iDDetalleParameter = iDDetalle.HasValue ?
                new ObjectParameter("IDDetalle", iDDetalle) :
                new ObjectParameter("IDDetalle", typeof(int));
    
            var numeroFacturaParameter = numeroFactura.HasValue ?
                new ObjectParameter("NumeroFactura", numeroFactura) :
                new ObjectParameter("NumeroFactura", typeof(int));
    
            var codigoCancionParameter = codigoCancion.HasValue ?
                new ObjectParameter("CodigoCancion", codigoCancion) :
                new ObjectParameter("CodigoCancion", typeof(int));
    
            var subtotalParameter = subtotal.HasValue ?
                new ObjectParameter("Subtotal", subtotal) :
                new ObjectParameter("Subtotal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarDetalleVenta", iDDetalleParameter, numeroFacturaParameter, codigoCancionParameter, subtotalParameter);
        }
    
        public virtual int EditarGenero(Nullable<int> codigoGenero, string nuevaDescripcion)
        {
            var codigoGeneroParameter = codigoGenero.HasValue ?
                new ObjectParameter("CodigoGenero", codigoGenero) :
                new ObjectParameter("CodigoGenero", typeof(int));
    
            var nuevaDescripcionParameter = nuevaDescripcion != null ?
                new ObjectParameter("NuevaDescripcion", nuevaDescripcion) :
                new ObjectParameter("NuevaDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarGenero", codigoGeneroParameter, nuevaDescripcionParameter);
        }
    
        public virtual int EliminarDetalleVenta(Nullable<int> iDDetalle)
        {
            var iDDetalleParameter = iDDetalle.HasValue ?
                new ObjectParameter("IDDetalle", iDDetalle) :
                new ObjectParameter("IDDetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarDetalleVenta", iDDetalleParameter);
        }
    
        public virtual int EliminarGenero(Nullable<int> codigoGenero)
        {
            var codigoGeneroParameter = codigoGenero.HasValue ?
                new ObjectParameter("CodigoGenero", codigoGenero) :
                new ObjectParameter("CodigoGenero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarGenero", codigoGeneroParameter);
        }
    
        public virtual int InsertarDetalleVenta(Nullable<int> numeroFactura, Nullable<int> codigoCancion, Nullable<decimal> subtotal)
        {
            var numeroFacturaParameter = numeroFactura.HasValue ?
                new ObjectParameter("NumeroFactura", numeroFactura) :
                new ObjectParameter("NumeroFactura", typeof(int));
    
            var codigoCancionParameter = codigoCancion.HasValue ?
                new ObjectParameter("CodigoCancion", codigoCancion) :
                new ObjectParameter("CodigoCancion", typeof(int));
    
            var subtotalParameter = subtotal.HasValue ?
                new ObjectParameter("Subtotal", subtotal) :
                new ObjectParameter("Subtotal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarDetalleVenta", numeroFacturaParameter, codigoCancionParameter, subtotalParameter);
        }
    
        public virtual int InsertarGenero(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarGenero", descripcionParameter);
        }
    
        public virtual ObjectResult<ListaGeneros_Result> ListaGeneros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaGeneros_Result>("ListaGeneros");
        }
    
        public virtual ObjectResult<ListarDetalleVenta_Result> ListarDetalleVenta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDetalleVenta_Result>("ListarDetalleVenta");
        }
    
        public virtual int spActualizarAlbum(Nullable<int> codigoAlbum, Nullable<int> codigoArtista, string nombreAlbum, Nullable<int> anoLanzamiento, string imagen)
        {
            var codigoAlbumParameter = codigoAlbum.HasValue ?
                new ObjectParameter("CodigoAlbum", codigoAlbum) :
                new ObjectParameter("CodigoAlbum", typeof(int));
    
            var codigoArtistaParameter = codigoArtista.HasValue ?
                new ObjectParameter("CodigoArtista", codigoArtista) :
                new ObjectParameter("CodigoArtista", typeof(int));
    
            var nombreAlbumParameter = nombreAlbum != null ?
                new ObjectParameter("NombreAlbum", nombreAlbum) :
                new ObjectParameter("NombreAlbum", typeof(string));
    
            var anoLanzamientoParameter = anoLanzamiento.HasValue ?
                new ObjectParameter("AnoLanzamiento", anoLanzamiento) :
                new ObjectParameter("AnoLanzamiento", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spActualizarAlbum", codigoAlbumParameter, codigoArtistaParameter, nombreAlbumParameter, anoLanzamientoParameter, imagenParameter);
        }
    
        public virtual int spActualizarArtista(Nullable<int> codigoArtista, string nombreArtistico, string fechaNacimiento, string nombreReal, string nacionalidad, string foto, string linkBiografia)
        {
            var codigoArtistaParameter = codigoArtista.HasValue ?
                new ObjectParameter("CodigoArtista", codigoArtista) :
                new ObjectParameter("CodigoArtista", typeof(int));
    
            var nombreArtisticoParameter = nombreArtistico != null ?
                new ObjectParameter("NombreArtistico", nombreArtistico) :
                new ObjectParameter("NombreArtistico", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento != null ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(string));
    
            var nombreRealParameter = nombreReal != null ?
                new ObjectParameter("NombreReal", nombreReal) :
                new ObjectParameter("NombreReal", typeof(string));
    
            var nacionalidadParameter = nacionalidad != null ?
                new ObjectParameter("Nacionalidad", nacionalidad) :
                new ObjectParameter("Nacionalidad", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(string));
    
            var linkBiografiaParameter = linkBiografia != null ?
                new ObjectParameter("LinkBiografia", linkBiografia) :
                new ObjectParameter("LinkBiografia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spActualizarArtista", codigoArtistaParameter, nombreArtisticoParameter, fechaNacimientoParameter, nombreRealParameter, nacionalidadParameter, fotoParameter, linkBiografiaParameter);
        }
    
        public virtual int spActualizarCancion(Nullable<int> codigoCancion, Nullable<int> codigoGenero, Nullable<int> codigoAlbum, string nombreCancion, string linkVideo, Nullable<decimal> precio, Nullable<int> cantidadDisponible)
        {
            var codigoCancionParameter = codigoCancion.HasValue ?
                new ObjectParameter("CodigoCancion", codigoCancion) :
                new ObjectParameter("CodigoCancion", typeof(int));
    
            var codigoGeneroParameter = codigoGenero.HasValue ?
                new ObjectParameter("CodigoGenero", codigoGenero) :
                new ObjectParameter("CodigoGenero", typeof(int));
    
            var codigoAlbumParameter = codigoAlbum.HasValue ?
                new ObjectParameter("CodigoAlbum", codigoAlbum) :
                new ObjectParameter("CodigoAlbum", typeof(int));
    
            var nombreCancionParameter = nombreCancion != null ?
                new ObjectParameter("NombreCancion", nombreCancion) :
                new ObjectParameter("NombreCancion", typeof(string));
    
            var linkVideoParameter = linkVideo != null ?
                new ObjectParameter("LinkVideo", linkVideo) :
                new ObjectParameter("LinkVideo", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var cantidadDisponibleParameter = cantidadDisponible.HasValue ?
                new ObjectParameter("CantidadDisponible", cantidadDisponible) :
                new ObjectParameter("CantidadDisponible", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spActualizarCancion", codigoCancionParameter, codigoGeneroParameter, codigoAlbumParameter, nombreCancionParameter, linkVideoParameter, precioParameter, cantidadDisponibleParameter);
        }
    
        public virtual int spActualizarUsuario(Nullable<int> iD, string numeroIdentificacion, string nombre, string apellido, string genero, string correoElectronico, string tipoTarjeta, Nullable<decimal> dineroDisponible, string numeroTarjeta, string contrasena, string perfil)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var numeroIdentificacionParameter = numeroIdentificacion != null ?
                new ObjectParameter("NumeroIdentificacion", numeroIdentificacion) :
                new ObjectParameter("NumeroIdentificacion", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var tipoTarjetaParameter = tipoTarjeta != null ?
                new ObjectParameter("TipoTarjeta", tipoTarjeta) :
                new ObjectParameter("TipoTarjeta", typeof(string));
    
            var dineroDisponibleParameter = dineroDisponible.HasValue ?
                new ObjectParameter("DineroDisponible", dineroDisponible) :
                new ObjectParameter("DineroDisponible", typeof(decimal));
    
            var numeroTarjetaParameter = numeroTarjeta != null ?
                new ObjectParameter("NumeroTarjeta", numeroTarjeta) :
                new ObjectParameter("NumeroTarjeta", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var perfilParameter = perfil != null ?
                new ObjectParameter("Perfil", perfil) :
                new ObjectParameter("Perfil", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spActualizarUsuario", iDParameter, numeroIdentificacionParameter, nombreParameter, apellidoParameter, generoParameter, correoElectronicoParameter, tipoTarjetaParameter, dineroDisponibleParameter, numeroTarjetaParameter, contrasenaParameter, perfilParameter);
        }
    
        public virtual int spAgregarArtista(string nombreArtistico, string fechaNacimiento, string nombreReal, string nacionalidad, string foto, string linkBiografia)
        {
            var nombreArtisticoParameter = nombreArtistico != null ?
                new ObjectParameter("NombreArtistico", nombreArtistico) :
                new ObjectParameter("NombreArtistico", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento != null ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(string));
    
            var nombreRealParameter = nombreReal != null ?
                new ObjectParameter("NombreReal", nombreReal) :
                new ObjectParameter("NombreReal", typeof(string));
    
            var nacionalidadParameter = nacionalidad != null ?
                new ObjectParameter("Nacionalidad", nacionalidad) :
                new ObjectParameter("Nacionalidad", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(string));
    
            var linkBiografiaParameter = linkBiografia != null ?
                new ObjectParameter("LinkBiografia", linkBiografia) :
                new ObjectParameter("LinkBiografia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAgregarArtista", nombreArtisticoParameter, fechaNacimientoParameter, nombreRealParameter, nacionalidadParameter, fotoParameter, linkBiografiaParameter);
        }
    
        public virtual int spAgregarCancion(Nullable<int> codigoGenero, Nullable<int> codigoAlbum, string nombreCancion, string linkVideo, Nullable<decimal> precio, Nullable<int> cantidadDisponible)
        {
            var codigoGeneroParameter = codigoGenero.HasValue ?
                new ObjectParameter("CodigoGenero", codigoGenero) :
                new ObjectParameter("CodigoGenero", typeof(int));
    
            var codigoAlbumParameter = codigoAlbum.HasValue ?
                new ObjectParameter("CodigoAlbum", codigoAlbum) :
                new ObjectParameter("CodigoAlbum", typeof(int));
    
            var nombreCancionParameter = nombreCancion != null ?
                new ObjectParameter("NombreCancion", nombreCancion) :
                new ObjectParameter("NombreCancion", typeof(string));
    
            var linkVideoParameter = linkVideo != null ?
                new ObjectParameter("LinkVideo", linkVideo) :
                new ObjectParameter("LinkVideo", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var cantidadDisponibleParameter = cantidadDisponible.HasValue ?
                new ObjectParameter("CantidadDisponible", cantidadDisponible) :
                new ObjectParameter("CantidadDisponible", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAgregarCancion", codigoGeneroParameter, codigoAlbumParameter, nombreCancionParameter, linkVideoParameter, precioParameter, cantidadDisponibleParameter);
        }
    
        public virtual int spAgregarUsuario(string numeroIdentificacion, string nombre, string apellido, string genero, string correoElectronico, string tipoTarjeta, Nullable<decimal> dineroDisponible, string numeroTarjeta, string contrasena, string perfil)
        {
            var numeroIdentificacionParameter = numeroIdentificacion != null ?
                new ObjectParameter("NumeroIdentificacion", numeroIdentificacion) :
                new ObjectParameter("NumeroIdentificacion", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var tipoTarjetaParameter = tipoTarjeta != null ?
                new ObjectParameter("TipoTarjeta", tipoTarjeta) :
                new ObjectParameter("TipoTarjeta", typeof(string));
    
            var dineroDisponibleParameter = dineroDisponible.HasValue ?
                new ObjectParameter("DineroDisponible", dineroDisponible) :
                new ObjectParameter("DineroDisponible", typeof(decimal));
    
            var numeroTarjetaParameter = numeroTarjeta != null ?
                new ObjectParameter("NumeroTarjeta", numeroTarjeta) :
                new ObjectParameter("NumeroTarjeta", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var perfilParameter = perfil != null ?
                new ObjectParameter("Perfil", perfil) :
                new ObjectParameter("Perfil", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAgregarUsuario", numeroIdentificacionParameter, nombreParameter, apellidoParameter, generoParameter, correoElectronicoParameter, tipoTarjetaParameter, dineroDisponibleParameter, numeroTarjetaParameter, contrasenaParameter, perfilParameter);
        }
    
        public virtual int spAgregarVenta(Nullable<int> iDUsuario, Nullable<System.DateTime> fechaCompra, Nullable<decimal> total, string tipoPago)
        {
            var iDUsuarioParameter = iDUsuario.HasValue ?
                new ObjectParameter("IDUsuario", iDUsuario) :
                new ObjectParameter("IDUsuario", typeof(int));
    
            var fechaCompraParameter = fechaCompra.HasValue ?
                new ObjectParameter("FechaCompra", fechaCompra) :
                new ObjectParameter("FechaCompra", typeof(System.DateTime));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("Total", total) :
                new ObjectParameter("Total", typeof(decimal));
    
            var tipoPagoParameter = tipoPago != null ?
                new ObjectParameter("TipoPago", tipoPago) :
                new ObjectParameter("TipoPago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAgregarVenta", iDUsuarioParameter, fechaCompraParameter, totalParameter, tipoPagoParameter);
        }
    
        public virtual int spEliminarAlbum(Nullable<int> codigoAlbum)
        {
            var codigoAlbumParameter = codigoAlbum.HasValue ?
                new ObjectParameter("CodigoAlbum", codigoAlbum) :
                new ObjectParameter("CodigoAlbum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarAlbum", codigoAlbumParameter);
        }
    
        public virtual int spEliminarArtista(Nullable<int> codigoArtista)
        {
            var codigoArtistaParameter = codigoArtista.HasValue ?
                new ObjectParameter("CodigoArtista", codigoArtista) :
                new ObjectParameter("CodigoArtista", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarArtista", codigoArtistaParameter);
        }
    
        public virtual int spEliminarCancion(Nullable<int> codigoCancion)
        {
            var codigoCancionParameter = codigoCancion.HasValue ?
                new ObjectParameter("CodigoCancion", codigoCancion) :
                new ObjectParameter("CodigoCancion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarCancion", codigoCancionParameter);
        }
    
        public virtual int spEliminarUsuario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarUsuario", idParameter);
        }
    
        public virtual int spInsertarAlbum(Nullable<int> codigoArtista, string nombreAlbum, Nullable<int> anoLanzamiento, string imagen)
        {
            var codigoArtistaParameter = codigoArtista.HasValue ?
                new ObjectParameter("CodigoArtista", codigoArtista) :
                new ObjectParameter("CodigoArtista", typeof(int));
    
            var nombreAlbumParameter = nombreAlbum != null ?
                new ObjectParameter("NombreAlbum", nombreAlbum) :
                new ObjectParameter("NombreAlbum", typeof(string));
    
            var anoLanzamientoParameter = anoLanzamiento.HasValue ?
                new ObjectParameter("AnoLanzamiento", anoLanzamiento) :
                new ObjectParameter("AnoLanzamiento", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarAlbum", codigoArtistaParameter, nombreAlbumParameter, anoLanzamientoParameter, imagenParameter);
        }
    
        public virtual ObjectResult<spListarAlbumes_Result> spListarAlbumes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spListarAlbumes_Result>("spListarAlbumes");
        }
    
        public virtual ObjectResult<spListarAlbumPorID_Result> spListarAlbumPorID(Nullable<int> codigoAlbum)
        {
            var codigoAlbumParameter = codigoAlbum.HasValue ?
                new ObjectParameter("CodigoAlbum", codigoAlbum) :
                new ObjectParameter("CodigoAlbum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spListarAlbumPorID_Result>("spListarAlbumPorID", codigoAlbumParameter);
        }
    
        public virtual ObjectResult<spMostrarArtistaPorId_Result> spMostrarArtistaPorId(Nullable<int> codigoArtista)
        {
            var codigoArtistaParameter = codigoArtista.HasValue ?
                new ObjectParameter("CodigoArtista", codigoArtista) :
                new ObjectParameter("CodigoArtista", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarArtistaPorId_Result>("spMostrarArtistaPorId", codigoArtistaParameter);
        }
    
        public virtual ObjectResult<spMostrarAuditoria_Result> spMostrarAuditoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarAuditoria_Result>("spMostrarAuditoria");
        }
    
        public virtual ObjectResult<spMostrarAuditoriaPorFecha_Result> spMostrarAuditoriaPorFecha(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarAuditoriaPorFecha_Result>("spMostrarAuditoriaPorFecha", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<spMostrarAuditoriaPorTabla_Result> spMostrarAuditoriaPorTabla(string tablaAfectada)
        {
            var tablaAfectadaParameter = tablaAfectada != null ?
                new ObjectParameter("TablaAfectada", tablaAfectada) :
                new ObjectParameter("TablaAfectada", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarAuditoriaPorTabla_Result>("spMostrarAuditoriaPorTabla", tablaAfectadaParameter);
        }
    
        public virtual ObjectResult<spMostrarCancionPorCodigo_Result> spMostrarCancionPorCodigo(Nullable<int> codigoCancion)
        {
            var codigoCancionParameter = codigoCancion.HasValue ?
                new ObjectParameter("CodigoCancion", codigoCancion) :
                new ObjectParameter("CodigoCancion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarCancionPorCodigo_Result>("spMostrarCancionPorCodigo", codigoCancionParameter);
        }
    
        public virtual ObjectResult<spMostrarTodasCanciones_Result> spMostrarTodasCanciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarTodasCanciones_Result>("spMostrarTodasCanciones");
        }
    
        public virtual ObjectResult<spMostrarTodosArtistas_Result> spMostrarTodosArtistas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarTodosArtistas_Result>("spMostrarTodosArtistas");
        }
    
        public virtual ObjectResult<spMostrarTodosUsuarios_Result> spMostrarTodosUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarTodosUsuarios_Result>("spMostrarTodosUsuarios");
        }
    
        public virtual ObjectResult<spMostrarUsuariosPorId_Result> spMostrarUsuariosPorId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarUsuariosPorId_Result>("spMostrarUsuariosPorId", idParameter);
        }
    
        public virtual ObjectResult<spMostrarVentaPorId_Result> spMostrarVentaPorId(Nullable<int> numeroFactura)
        {
            var numeroFacturaParameter = numeroFactura.HasValue ?
                new ObjectParameter("NumeroFactura", numeroFactura) :
                new ObjectParameter("NumeroFactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarVentaPorId_Result>("spMostrarVentaPorId", numeroFacturaParameter);
        }
    
        public virtual ObjectResult<spMostrarVentas_Result> spMostrarVentas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMostrarVentas_Result>("spMostrarVentas");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
