//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int ID { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Genero { get; set; }
        public string CorreoElectronico { get; set; }
        public string TipoTarjeta { get; set; }
        public decimal DineroDisponible { get; set; }
        public string NumeroTarjeta { get; set; }
        public string Contrasena { get; set; }
        public string Perfil { get; set; }
    
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
