//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    using VentaMusical.Models.ViewModels.Canciones;

    public partial class Ventas
    {
        public Ventas()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int NumeroFactura { get; set; }
        public int IDUsuario { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public string TipoPago { get; set; }
        public decimal TotalSinIVA { get; set; }
        public decimal IVA { get; set; }
        public decimal RecargoTarjeta { get; set; }
        public decimal TotalFinal { get; set; }
        public string CodigoTarjeta { get; set; }
        public Nullable<decimal> MontoCreditoUsado { get; set; }
        public Nullable<decimal> MontoRestante { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> EnviadaPorCorreo { get; set; }
        public Nullable<decimal> TotalConCredito { get; set; }
        public Nullable<System.DateTime> FechaEnvioCorreo { get; set; }
    
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual Usuarios Usuarios { get; set; }

        public int CodigoCancion { get; set; }
        public virtual Cancion Cancion { get; set; }

    }
}
